// SPDX-License-Identifier: MIT
/*
 * Copyright © 2020 Intel Corporation
 *
 * Generated by: IGT Gpu Tools on Fri 21 Feb 2020 05:30:13 AM UTC
 */

static const u32 hsw_clear_kernel[] = {
	/*(DEBLOBBED)*/
};
