/*
 * Declare these here even if Tigon I support is disabled to avoid
 * the compiler complaining about undefined symbols.
 */
#define tigonFwReleaseMajor 0xc
#define tigonFwReleaseMinor 0x4
#define tigonFwReleaseFix 0xb
/*(DEBLOBBED)*/
#ifdef CONFIG_ACENIC_OMIT_TIGON_I
#define tigonFwText NULL
#define tigonFwData NULL
#define tigonFwRodata NULL
#else
/* Generated by genfw.c */
/*(DEBLOBBED)*/
#endif
/* Generated by genfw.c */
#define tigon2FwReleaseMajor 0xc
#define tigon2FwReleaseMinor 0x4
#define tigon2FwReleaseFix 0xb
/*(DEBLOBBED)*/
/*(DEBLOBBED)*/
